      <datalist id="locais">
      <option value="Avenida Gabriela Prado Maia Ribeiro">
      <option value="Avenida Heitor Beltrão">
      <option value="Avenida Maracanã">
      <option value="Avenida Maracanã (NR)">
          <option value="Avenida Melo e Matos">
      <option value="Bairro Gratidão">
      <option value="Beco Abacate da Formiga">
      <option value="Beco Alcides Ramos da Silva">
          <option value="Beco Ameixa da Formiga">
      <option value="Beco Ary dos Santos">
      <option value="Beco Cravo da Formiga">
      <option value="Beco da Coruja (NR)">
          <option value="Beco Edite Maria da Silva">
      <option value="Beco H4">
      <option value="Beco Jabuticaba da Formiga">
      <option value="Beco Jaca da Formiga">
          <option value="Beco Jamelão da Formiga">
      <option value="Beco Jasmim da Formiga">
      <option value="Beco João Gomes Thomaz">
      <option value="Beco Jorge Gomes">
           <option value="Beco José Amâncio da Silva">
      <option value="Beco Laranja da Formiga">
      <option value="Beco Limão da Formiga">
          <option value="Beco Maçã da Formiga ">
      <option value="Beco Manga da Formiga">
      <option value="Beco Melancia da Formiga">
      <option value="Beco Melão da Formiga">
          <option value="Beco Pera da Formiga">
      <option value="Beco Rosa da Formiga">
      <option value="Beco Uva da Formiga">
      <option value="Beco Violeta da Formiga">
          <option value="Centro Comercial Iskye">
      <option value="Condomínio Juiz Pedro Namorado">
      <option value="Condomínio Vila Nova">
      <option value="Coronel Correa Lima">
           <option value="Estrada da Casa Branca">
          <option value="Estrada da Chácara do Céu">
      <option value="Estrada da Independência da Chácara">
      <option value="Estrada da Independência do Borel">
      <option value="Largo Atumã">
          <option value="Largo da Bíblia (NR)">
      <option value="Largo Frei Cassiano Villarosa">
      <option value="Largo Professor Gondim Neto">
      <option value="Praça Barão de Corumbá">
           <option value="Praça Carlos Paolera">
          <option value="Praça Celso da Rocha Miranda">
      <option value="Praça Comandante Xavier de Brito">
      <option value="Praça Itororó">
      <option value="Praça Lamartine Babo">
          <option value="Praça Luís La Saigne">
      <option value="Praça Saenz Peña">
      <option value="Praça Tabatinga">
      <option value="Praça Varnhagen">
           <option value="Rua Abelardo Chacrinha Barbosa">
          <option value="Rua Abreu Viana">
      <option value="Rua Adolfo Mota">
      <option value="Rua Afonso Pena">
      <option value="Rua Agostinho">
          <option value="Rua Aguiar">
      <option value="Rua Aires Gomes">
      <option value="Rua Alberto de Sequeira">
      <option value="Rua Alda Melo Dias (NR)">
           <option value="Rua Aldo do Couto Aires (NR)">
          <option value="Rua Alexandre de Gusmão">
      <option value="Rua Alfredo Pinto">
      <option value="Rua Almirante Cóchrane">
      <option value="Rua Almirante Gavião">
          <option value="Rua Alves de Brito">
      <option value="Rua Alves de Souza (NR)">
      <option value="Rua Alzira Brandão">
      <option value="Rua Amoroso Costa">
               <option value="Rua Andrade Neves">
      <option value="Rua Antônio Albino de Souza (NR)">
      <option value="Rua Antônio Basílio">
      <option value="Rua Antônio Bello Filho)">
          <option value="Rua Antonio Pinto da Mota">
      <option value="Rua Araújo Pena">
      <option value="Rua Ary Kerner">
      <option value="Rua Ângelo Agostini">
          <option value="Rua Babilônia">
      <option value="Rua Barão de Itapagipe">
      <option value="Rua Barão de Mesquita">
      <option value="Rua Barão de Pirassinunga">
          <option value="Rua Basilieia">
      <option value="Rua Belvedere">
      <option value="Rua Benjamin Franklin">
      <option value="Rua Bom Pastor">
          <option value="Rua Caetano de Campos">
      <option value="Rua Camaioré">
      <option value="Rua Camaragibe">
      <option value="Rua Campos Sales">
           <option value="Rua Camutanga">
      <option value="Rua Camutanga (NR)">
      <option value="Rua Canuto Saraiva">
          <option value="Rua Carlos de Laet ">
      <option value="Rua Carlos de Vasconcelos">
      <option value="Rua Carmela Dutra">
      <option value="Rua Caruso">
          <option value="Rua Carvalho Alvim">
      <option value="Rua Castelnuovo">
      <option value="Rua Castelnuovo (NR)">
      <option value="Rua Clóvis Bevilaqua">
          <option value="Rua Clemente Falcão">
      <option value="Rua Comandante Prat">
      <option value="Rua Conde de Bonfim">
      <option value="Rua Conde de Itaguaí">
           <option value="Rua Condeuba">
          <option value="Rua Conselheiro Zenha">
      <option value="Rua Coronel Aristarcho Pessoa">
      <option value="Rua Cotingo">
      <option value="Rua da Cascata">
          <option value="Rua da Cascata (NR)">
      <option value="Rua da Criança da Chácara do Céu">
      <option value="Rua da Floresta da Chácara do Céu">
      <option value="Rua das Flores">
           <option value="Rua Delgado de Carvalho">
          <option value="Rua Deputado Soares Filho">
      <option value="Rua Desembargador Izidro">
      <option value="Rua Dezoito de Outubro">
      <option value="Rua do Bispo">
          <option value="Rua do Campo">
      <option value="Rua do Contorno (NR)">
      <option value="Rua do Ico">
      <option value="Rua do Pinheiro da Chácara do Céu">
           <option value="Rua Domício da Gama">
          <option value="Rua Dona Delfina">
      <option value="Rua dos Araújos">
      <option value="Rua dos Araújos, 71">
      <option value="Rua dos Araujos Numeros">
          <option value="Rua Doutor Abelardo de Barros">
      <option value="Rua Doutor Aníbal Moreira">
      <option value="Rua Doutor Dilermando Cruz">
      <option value="Rua Doutor Oscar Pimentel">
           <option value="Rua Doutor Otávio Kelly">
          <option value="Rua Doutor Pereira dos Santos">
      <option value="Rua Doutor Renato Rocco">
      <option value="Rua Doutor Satamini">
      <option value="Rua Dulce">
          <option value="Rua Eduardo Ramos">
      <option value="Rua Elias Diuana">
      <option value="Rua Embaixador Ramon Carcand">
      <option value="Rua Enes de Souza">
          <option value="Rua Engenheiro Adel">
      <option value="Rua Engenheiro Cavalcânti">
      <option value="Rua Engenheiro Enaldo Cravo Peixoto">
      <option value="Rua Engenheiro Ernani Cotrin">
           <option value="Rua Ernesto Sena">
          <option value="Rua Esperança da Chácara do Céu">
      <option value="Rua Félix da Cunha">
      <option value="Rua Felicidade da Chácara do Céu">
      <option value="Rua Felipe Cordeiro (NR)">
          <option value="Rua Ferdinando Laboriau">
      <option value="Rua Fernandes Figueira">
      <option value="Rua Fernandes Vieira">
      <option value="Rua França Júnior">
          <option value="Rua Francisco Graça">
      <option value="Rua Francisco Silva (NR)">
      <option value="Rua Gargau">
      <option value="Rua Garibaldi">
           <option value="Rua General Espírito Santo Cardoso">
          <option value="Rua General Marcelino">
      <option value="Rua General Roca">
      <option value="Rua General Silva Pessoa">
      <option value="Rua Gonçalves Crespo">
          <option value="Rua Goulart">
      <option value="Rua Guajaratuba">
      <option value="Rua Guapeni">
      <option value="Rua Guapiara">
          <option value="Rua Guaxupé">
      <option value="Rua Gurindiba">
      <option value="Rua Haddock Lobo">
      <option value="Rua Henrique Fleiuss">
           <option value="Rua Henry Ford">
          <option value="Rua Homem de Melo">
      <option value="Rua Itacuruçá">
      <option value="Rua Jacuma">
      <option value="Rua Jair Lima Gonçalves (NR)">
          <option value="Rua Joaquim Pizarro">
      <option value="Rua João Alfredo">
      <option value="Rua João da Mata">
      <option value="Rua João Ramalho">
                    <option value="Rua João Ramos da Rocha (NR)">
      <option value="Rua Jocelina Fernandes">
      <option value="Rua Jorge Lossio">
      <option value="Rua José Gerônimo Afonso (NR)">
           <option value="Rua José Higino">
          <option value="Rua José Olice (NR)">
      <option value="Rua Junquilhos">
      <option value="Rua Jurupari">
      <option value="Rua Leite de Abreu">
          <option value="Rua Livreiro Francisco Alves">
      <option value="Rua Maestro Villa Lobos">
      <option value="Rua Major Ávila">
      <option value="Rua Manoel Leitão">
                    <option value="Rua Manoel Soares (NR)">
      <option value="Rua Marechal Marques Porto">
      <option value="Rua Marechal Taumaturgo de Azevedo">
      <option value="Rua Marechal Trompowski">
           <option value="Rua Maria Amália">
          <option value="Rua Mariz e Barros">
      <option value="Rua Marquês de Valença">
      <option value="Rua Martins Pena">
      <option value="Rua Matilde">
          <option value="Rua Max Fleiuss">
      <option value="Rua Mário Barreto">
      <option value="Rua Mário de Alencar">
      <option value="Rua Medeiros Pássaro">
                    <option value="Rua Moacir de Souza (NR)">
      <option value="Rua Monsenhor Battistoni">
      <option value="Rua Monsenhor MacDowell">
      <option value="Rua Morales de Los Rios">
           <option value="Rua Moura Brito">
          <option value="Rua Natalina">
      <option value="Rua Olavo Menezes (NR)">
      <option value="Rua Olímpia">
      <option value="Rua Olegario Mariano">
          <option value="Rua Oliveira da Silva">
      <option value="Rua Padre Elias Gorayeb">
      <option value="Rua Palmira Gonçalves Maia">
      <option value="Rua Pardal Mallet">
                    <option value="Rua Pareto">
      <option value="Rua Patativa (NR)">
      <option value="Rua Paul Underberg">
      <option value="Rua Paulino Nogueira">
           <option value="Rua Paulo Roberto Lima (NR)">
          <option value="Rua Pereira Barreto">
      <option value="Rua Pereira de Siqueira">
      <option value="Rua Pinheiro da Cunha">
      <option value="Rua Pinto de Figueiredo">
          <option value="Rua Pinto Guedes">
      <option value="Rua Piracicaba">
      <option value="Rua Potengi">
      <option value="Rua Professor Gabizo">
          <option value="Rua Professor Helion Póvoa">
      <option value="Rua Professor Lafayette Cortês">
      <option value="Rua Professor Pizarro">
           <option value="Rua Radmaker">
          <option value="Rua Raul Alves de Souza (NR)">
      <option value="Rua Rego Lopes">
      <option value="Rua Ribeirão Preto">
      <option value="Rua Rocha Miranda">
          <option value="Rua Rosário (NR)">
      <option value="Rua Rubens Domingues (NR)">
      <option value="Rua Rubens Rodrigues (NR)">
      <option value="Rua Sabóia Lima">
          <option value="Rua Santa Carolina">
      <option value="Rua Santa Sofia">
      <option value="Rua Santo Afonso">
           <option value="Rua São Francisco Xavier">
          <option value="Rua São Miguel">
      <option value="Rua São Rafael">
      <option value="Rua São Vicente">
      <option value="Rua Severino Brandão">
          <option value="Rua Silva Cordeiro (NR)">
      <option value="Rua Silva Guimarães">
      <option value="Rua Silva M. Trindade">
      <option value="Rua Silva M. Trindade (NR)">
           <option value="Rua Silva Ramos">
          <option value="Rua Soares da Costa">
      <option value="Rua Soprasasso">
      <option value="Rua Soriano de Sousa">
      <option value="Rua Tenente Marques de Souza">
          <option value="Rua Tenente Vilas-Boas">
      <option value="Rua Thiago Gonçalves">
      <option value="Rua Thiago Gonçalves (NR)">
      <option value="Rua Tiaçu">
           <option value="Rua Tobias Moscoso">
          <option value="Rua Urbano Duarte">
      <option value="Rua Uruguai">
      <option value="Rua Valdir de Oliveira">
      <option value="Rua Valparaíso">
          <option value="Rua Vicente Licínio">
      <option value="Rua Virgínia de Assis (NR)">
      <option value="Rua Visconde de Cabo Frio">
      <option value="Rua Visconde de Figueiredo">
     </datalist>